-- 코드를 입력하세요
SELECT A.NAME,A.DATETIME
FROM ANIMAL_INS AS A
LEFT OUTER JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE (A.DATETIME IS NOT NULL) AND (B.DATETIME IS NULL)
ORDER BY A.DATETIME
LIMIT 3;
# SELECT *
# FROM ANIMAL_OUTS