-- 코드를 입력하세요
SELECT A.PRODUCT_ID,PRODUCT_NAME, SUM(AMOUNT) * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT A 
JOIN FOOD_ORDER B
ON A.PRODUCT_ID = B.PRODUCT_ID
# WHERE B.IN_DATE >= '2022-01-01' AND B.IN_DATE < '2023-01-01'
WHERE PRODUCE_DATE LIKE '2022-05-%'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC

/* 배운점
1.명확하게 A테이블 안의 컬럼인지 B테이블 안의 컬럼인지 정해줘야하는 경우(둘다 있는 경우)에만 A. 
하면 되고, 아니면 그냥 컬럼명 써도 된다.

2. WHERE 절이 GROUP BY보다 앞에 와야함.